apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}

    http {
      server {
        listen 80;
        server_name _;
        location = /auth { return 301 /auth/; }
        location /auth/ { proxy_pass http://auth:8001/; }
        location / { proxy_pass http://shortener:8000; }
      }
    }
