apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}

    http {
      limit_req_zone $binary_remote_addr zone=mylimit:10m rate=100r/s;
      limit_req_status 429;

      server {
        listen 80;
        server_name _;
        location = /auth { return 301 /auth/; }
        location /auth/ {
          limit_req zone=mylimit burst=50 nodelay;
          proxy_pass http://auth:8001/;
        }
        location / {
          limit_req zone=mylimit burst=50 nodelay;
          proxy_pass http://shortener:8000;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
