apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: cG9zdGdyZXM=
  JWT_SECRET_KEY: ZHVtbXktc2VjcmV0LWtleS1hdC1sZWFzdC0yNTYtYml0cy1sb25n
