events {}

http {
  limit_req_zone $binary_remote_addr zone=mylimit:10m rate=100r/s;
  limit_req_status 429;

  server {
    listen 80;
    server_name _;
    location = /auth { return 301 /auth/; }
    location /auth/ {
        limit_req zone=mylimit burst=200 nodelay;
        proxy_pass http://auth:8001/;
      }
    location / {
        limit_req zone=mylimit burst=200 nodelay;
        proxy_pass http://shortener:8000;
      }
  }
}